
---

## 🧾 `LICENSE.md` (S.U.E.T. – Fully Open Use License)

markdown
# Sovereign Universal Entity Technical License (S.U.E.T.)

Permission is hereby granted to anyone to use, modify, compile, or redistribute this code for free or commercial use, provided:

- Attribution to the original Clashup project is maintained.
- Derivative works remain open-source under this same license.

This software is provided "as is", without warranty.



name: Clashup CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-clashup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Run Playground Server Test
      run: python -m clashc.main tests/test.clsh
